python src/evaluator.py --benchmark bbq --category age --model_name meta-llama/Meta-Llama-3-70B --method self_explanation --test disambig --precentage 10
python src/evaluator.py --benchmark bbq --category disability_status --model_name meta-llama/Meta-Llama-3-70B --method self_explanation --test disambig --precentage 10
python src/evaluator.py --benchmark bbq --category gender_identity --model_name meta-llama/Meta-Llama-3-70B --method self_explanation --test disambig --precentage 10
python src/evaluator.py --benchmark bbq --category nationality --model_name meta-llama/Meta-Llama-3-70B --method self_explanation --test disambig --precentage 10
python src/evaluator.py --benchmark bbq --category physical_appearance --model_name meta-llama/Meta-Llama-3-70B --method self_explanation --test disambig --precentage 10
python src/evaluator.py --benchmark bbq --category race_ethnicity --model_name meta-llama/Meta-Llama-3-70B --method self_explanation --test disambig --precentage 10
python src/evaluator.py --benchmark bbq --category religion --model_name meta-llama/Meta-Llama-3-70B --method self_explanation --test disambig --precentage 10
python src/evaluator.py --benchmark bbq --category ses --model_name meta-llama/Meta-Llama-3-70B --method self_explanation --test disambig --precentage 10
python src/evaluator.py --benchmark bbq --category sexual_orientation --model_name meta-llama/Meta-Llama-3-70B --method self_explanation --test disambig --precentage 10
python src/evaluator.py --benchmark bbq --category race_x_ses --model_name meta-llama/Meta-Llama-3-70B --method self_explanation --test disambig --precentage 10
python src/evaluator.py --benchmark bbq --category race_x_gender --model_name meta-llama/Meta-Llama-3-70B --method self_explanation --test disambig --precentage 10